"""Minimal AppKit stub for PyObjC migration. All attributes are Any."""

from typing import Any

class NSWindow:
    """Stub for AppKit.NSWindow."""

    @classmethod
    def alloc(cls) -> Any: ...
    def initWithContentRect_styleMask_backing_defer_(
        self, rect: Any, style: Any, backing: Any, defer: Any
    ) -> Any: ...
    def setTitle_(self, title: str) -> None: ...
    def setReleasedWhenClosed_(self, flag: bool) -> None: ...
    def contentView(self) -> Any: ...
    def makeKeyAndOrderFront_(self, obj: Any) -> None: ...

class NSButton:
    """Stub for AppKit.NSButton."""

    ...

class NSTableView:
    """Stub for AppKit.NSTableView."""

    @classmethod
    def alloc(cls) -> Any: ...
    def initWithFrame_(self, frame: Any) -> Any: ...
    def addTableColumn_(self, column: Any) -> None: ...
    def setDelegate_(self, delegate: Any) -> None: ...
    def setDataSource_(self, data_source: Any) -> None: ...
    def reloadData(self) -> None: ...
    def selectedRow(self) -> int: ...

class NSTableColumn:
    """Stub for AppKit.NSTableColumn."""

    @classmethod
    def alloc(cls) -> Any: ...
    def initWithIdentifier_(self, identifier: str) -> Any: ...
    def setWidth_(self, width: float) -> None: ...
    def headerCell(self) -> Any: ...
    def identifier(self) -> Any: ...

class NSSearchField:
    """Stub for AppKit.NSSearchField."""

    @classmethod
    def alloc(cls) -> Any: ...
    def initWithFrame_(self, frame: Any) -> Any: ...
    def init(self) -> Any: ...
    def cell(self) -> Any: ...
    def setDelegate_(self, delegate: Any) -> None: ...
    def stringValue(self) -> str: ...
    def setStringValue_(self, value: str) -> None: ...

class NSSegmentedControl:
    """Stub for AppKit.NSSegmentedControl."""

    @classmethod
    def alloc(cls) -> Any: ...
    def initWithFrame_(self, frame: Any) -> Any: ...
    def init(self) -> Any: ...
    def setSegmentCount_(self, count: int) -> None: ...
    def setLabel_forSegment_(self, label: str, segment: int) -> None: ...
    def setWidth_forSegment_(self, width: float, segment: int) -> None: ...
    def setTrackingMode_(self, mode: int) -> None: ...
    def setSegmentStyle_(self, style: Any) -> None: ...
    def sizeToFit(self) -> None: ...
    def setTarget_(self, target: Any) -> None: ...
    def setAction_(self, action: Any) -> None: ...
    def selectedSegment(self) -> int: ...

class NSScrollView:
    """Stub for AppKit.NSScrollView."""

    @classmethod
    def alloc(cls) -> Any: ...
    def initWithFrame_(self, frame: Any) -> Any: ...
    def init(self) -> Any: ...
    def setHasVerticalScroller_(self, flag: bool) -> None: ...
    def setHasHorizontalScroller_(self, flag: bool) -> None: ...
    def setBorderType_(self, border_type: Any) -> None: ...
    def setAutoresizingMask_(self, mask: Any) -> None: ...
    def setDocumentView_(self, view: Any) -> None: ...

def __getattr__(name: str) -> Any: ...
