"""Type stubs for AppKit framework."""

from typing import Any, Callable, List, Optional, Protocol, Tuple, Union

# Constants
NSViewWidthSizable: int
NSViewHeightSizable: int
NSBezelBorder: int
NSSegmentStyleRounded: int

class NSObject:
    """Base class for all Objective-C objects."""
    
    def alloc(self) -> "NSObject": ...
    def init(self) -> "NSObject": ...
    def setDelegate_(self, delegate: Any) -> None: ...
    def delegate(self) -> Any: ...

class NSControl(NSObject):
    """Base class for controls in AppKit."""
    
    def initWithFrame_(self, frame: Any) -> "NSControl": ...
    def setTarget_(self, target: Any) -> None: ...
    def setAction_(self, action: Any) -> None: ...
    def target(self) -> Any: ...
    def action(self) -> Any: ...

class NSView(NSObject):
    """Base class for views in AppKit."""
    
    def initWithFrame_(self, frame: Any) -> "NSView": ...
    def addSubview_(self, view: NSView) -> None: ...
    def setAutoresizingMask_(self, mask: int) -> None: ...
    def autoresizingMask(self) -> int: ...
    def setFrame_(self, frame: Any) -> None: ...
    def frame(self) -> Any: ...

class NSSearchField(NSControl):
    """Search field control in AppKit."""
    
    def initWithFrame_(self, frame: Any) -> "NSSearchField": ...
    def cell(self) -> NSSearchFieldCell: ...
    def setStringValue_(self, value: str) -> None: ...
    def stringValue(self) -> str: ...

class NSSearchFieldCell(NSObject):
    """Cell for NSSearchField."""
    
    def setPlaceholderString_(self, placeholder: str) -> None: ...
    def placeholderString(self) -> str: ...

class NSTableView(NSControl):
    """Table view control in AppKit."""
    
    def initWithFrame_(self, frame: Any) -> "NSTableView": ...
    def addTableColumn_(self, column: NSTableColumn) -> None: ...
    def setDataSource_(self, dataSource: Any) -> None: ...
    def dataSource(self) -> Any: ...
    def reloadData(self) -> None: ...

class NSTableColumn(NSObject):
    """Column for NSTableView."""
    
    def initWithIdentifier_(self, identifier: str) -> "NSTableColumn": ...
    def setWidth_(self, width: float) -> None: ...
    def width(self) -> float: ...
    def headerCell(self) -> NSTableHeaderCell: ...

class NSTableHeaderCell(NSObject):
    """Header cell for NSTableColumn."""
    
    def setStringValue_(self, value: str) -> None: ...
    def stringValue(self) -> str: ...

class NSScrollView(NSView):
    """Scroll view container in AppKit."""
    
    def initWithFrame_(self, frame: Any) -> "NSScrollView": ...
    def setHasVerticalScroller_(self, has: bool) -> None: ...
    def setHasHorizontalScroller_(self, has: bool) -> None: ...
    def setBorderType_(self, type: int) -> None: ...
    def setDocumentView_(self, view: NSView) -> None: ...
    def documentView(self) -> NSView: ...

class NSSegmentedControl(NSControl):
    """Segmented control in AppKit."""
    
    def initWithFrame_(self, frame: Any) -> "NSSegmentedControl": ...
    def setSegmentCount_(self, count: int) -> None: ...
    def segmentCount(self) -> int: ...
    def setLabel_forSegment_(self, label: str, segment: int) -> None: ...
    def labelForSegment_(self, segment: int) -> str: ...
    def setWidth_forSegment_(self, width: float, segment: int) -> None: ...
    def widthForSegment_(self, segment: int) -> float: ...
    def setSelectedSegment_(self, segment: int) -> None: ...
    def selectedSegment(self) -> int: ...
    def setTrackingMode_(self, mode: int) -> None: ...
    def trackingMode(self) -> int: ...
    def setSegmentStyle_(self, style: int) -> None: ...
    def segmentStyle(self) -> int: ...
    def sizeToFit(self) -> None: ... 