name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    - name: Build and package
      run: |
        python -m build
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/panoptikon-${{ github.ref_name }}.tar.gz
        asset_name: panoptikon-${{ github.ref_name }}.tar.gz
        asset_content_type: application/gzip
    # To enable PyPI publishing:
    # 1. Go to GitHub repository settings > Secrets and variables > Actions
    # 2. Add a new repository secret named PYPI_TOKEN with your PyPI API token
    - name: Publish to PyPI
      if: startsWith(github.ref, 'refs/tags/') && env.PYPI_PUBLISH == 'true'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_TOKEN }}
        skip-existing: true
      env:
        PYPI_PUBLISH: ${{ secrets.PYPI_TOKEN != '' }} 