name: Self-Hosted Runner Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: self-hosted  # Uses the self-hosted runner
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      # We assume Python is already installed on the self-hosted runner
      run: |
        python --version
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f pyproject.toml ]; then pip install -e ".[dev]"; fi
        
    - name: Run tests
      run: |
        pytest tests/
        
    - name: Type check with mypy
      run: |
        mypy src/panoptikon
        
    - name: Lint with ruff
      run: |
        ruff check src/ 